name: Create Cypress report

on:
  push:
    branches:
      - main

jobs:
  cypress-generate-report:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Cypress run tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: | 
          mkdir public
          cp -r cypress/videos public/videos 

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'